---
- name: Create install location for WP-CLI
  run_once: true
  file: dest=/usr/share/wp-cli mode=755 owner=root group=root state=directory

- name: Install WP-CLI
  run_once: true
  get_url:
    url: https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
    dest: /usr/share/wp-cli/wp

- name: Set execute bits on WP-CLI
  file:
    path: /usr/share/wp-cli/wp
    mode: '0755'

- name: Symlink WP-CLI
  run_once: true
  file: dest=/usr/local/bin/wp src=/usr/share/wp-cli/wp state=link
