---
- name: restart memcached
  service:
    name: memcached
    state: restarted

- name: reload php-fpm
  service:
    name: php7.3-fpm
    state: reloaded

- name: reload nginx
  include: reload_nginx.yml
